workflows:
  Server-Linux-Docker-Hub-Release:
    name: Server Linux Docker Hub Release
    working_directory: src/ci_cd_utils_server
    instance_type: linux
    max_build_duration: 15
    labels:
      - PUBLIC_RELEASE
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*-release'
          include: true
        - pattern: '*-docker'
          include: true
    environment:
      groups:
        - DOCKER_HUB_CREDENTIALS
      flutter: 3.7.6
      vars:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
    scripts:
      - name: Authenticate with Docker Hub
        script: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - name: Build container and push to Docker Hub
        script: |
          export APP_VERSION=$(echo $CM_TAG | sed "s/-release\|-docker//g")
          echo "CM_TAG: $CM_TAG"
          echo "APP_VERSION: $APP_VERSION"
          docker buildx ls
          docker buildx create --use default
          docker buildx build --push --platform=linux/amd64,linux/arm64,linux/arm/v7 -f Dockerfile -t ranierjardim/ci_cd_utils:$APP_VERSION -t ranierjardim/ci_cd_utils:latest .
    publishing:
      email:
        recipients:
          - ranierjardim@gmail.com
        notify:
          success: true
          failure: true