workflows:
  Linux-Docker-Hub-Release:
    name: Linux Docker Hub Release
    working_directory: src/ci_cd_utils_server
    instance_type: linux
    max_build_duration: 15
    labels:
      - PUBLIC_RELEASE
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*-release'
          include: true
        - pattern: '*-docker'
          include: true
    environment:
      groups:
        - DOCKER_HUB_CREDENTIALS
      flutter: 3.7.6
      vars:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
    scripts:
      - name: Authenticate with Docker Hub
        script: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - name: Build container
        script: |
          make server_container_build_multi_platform
      - name: Upload and release on Docker Hub
        script: |
          export APP_VERSION=$(echo $CM_TAG | sed "s/-release\|-docker//g")
          echo "CM_TAG: $CM_TAG"
          echo "APP_VERSION: $APP_VERSION"
          make server_container_publish VERSION=$APP_VERSION
    publishing:
      email:
        recipients:
          - ranierjardim@gmail.com
        notify:
          success: true
          failure: true
  Linux-Snap-Store-Release:
    name: Linux Snap Store Release
    working_directory: src/app
    instance_type: linux
    max_build_duration: 15
    labels:
      - PUBLIC_RELEASE
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*-release'
          include: true
        - pattern: '*-linux'
          include: true
    environment:
      groups:
        - SNAP_CRED
      flutter: 3.7.6
      vars:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
    scripts:
      - name: Authenticate with Snap Store
        script: |
          echo $SNAPCRAFT_LOGIN_CREDENTIALS | base64 --decode > /home/builder/snapcraft-login-credentials
          snapcraft login --with /home/builder/snapcraft-login-credentials
      - name: Create a snap
        script: |
          export APP_VERSION=$(echo $CM_TAG | sed "s/-release\|-linux//g")
          echo "CM_TAG: $CM_TAG"
          echo "APP_VERSION: $APP_VERSION"
          export APP_GRADE="stable"
          snapcraft snap --output api-mocker-gateway.snap
      - name: Upload and release
        script: snapcraft upload api-mocker-gateway.snap
    publishing:
      email:
        recipients:
          - ranierjardim@gmail.com
        notify:
          success: true
          failure: true
  Windows-Microsoft-Store-Release:
    name: Windows Microsoft Store Release
    working_directory: src/app
    instance_type: windows_x2
    max_build_duration: 15
    labels:
      - PUBLIC_RELEASE
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*-release'
          include: true
        - pattern: '*-windows'
          include: true
    environment:
      groups:
        - MICROSOFT_STORE_CREDENTIALS
      flutter: 3.7.6
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Package Windows
        script: |
          $CM_TAG = [System.Environment]::GetEnvironmentVariable('CM_TAG')
          echo "CM_TAG: $CM_TAG"
          $APP_VERSION = $CM_TAG -replace '-release|-windows',''
          echo "APP_VERSION: $APP_VERSION"
          flutter pub run msix:create --version "$APP_VERSION.0"
    artifacts:
      - build/windows/**/*.msix
    publishing:
      partner_center:
        store_id: $STORE_ID
        tenant_id: $TENANT_ID
        client_id: $CLIENT_ID
        client_secret: $PARTNER_CLIENT_SECRET
      email:
        recipients:
          - ranierjardim@gmail.com
        notify:
          success: true
          failure: true
  macOS-App-Store-Release:
    name: macOS App Store Release
    working_directory: src/app
    instance_type: mac_mini
    max_build_duration: 15
    labels:
      - PUBLIC_RELEASE
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*-release'
          include: true
        - pattern: '*-mac'
          include: true
    integrations:
      app_store_connect: Codemagic CI
    environment:
      flutter: 3.7.6
      xcode: latest
      cocoapods: default
      groups:
        - APP_STORE_APP_INFO
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch Mac App Distribution certificate and Mac App Store profile
        script: |
          app-store-connect fetch-signing-files \
            $BUNDLE_ID \
            --platform MAC_OS \
            --type MAC_APP_STORE \
            --create
      - name: Fetch Mac Installer Distribution certificates
        script: |
          app-store-connect list-certificates --type MAC_INSTALLER_DISTRIBUTION --save
          # app-store-connect create-certificate --type MAC_INSTALLER_DISTRIBUTION --save
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build Flutter macOS
        script: |
          export APP_VERSION=`echo "$CM_TAG" | sed 's/-release//g; s/-mac//g'`
          flutter build macos --release --build-name=$APP_VERSION --build-number=0
      - name: Package macOS application
        script: |
          set -x
          # Command to find the path to your generated app
          APP_NAME=$(find $(pwd) -name "*.app")
          cd $(dirname "$APP_NAME")
          PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
          # Create an unsigned package
          xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg
          # Find the installer certificate commmon name in keychain
          LISTA_CERTIFICADOS=$(keychain list-certificates)
          INSTALLER_CERT_NAME=$(keychain list-certificates \
            | jq '.[]
            | select(.common_name
            | contains("Mac Developer Installer"))
            | .common_name' \
            | xargs)
          # Sign the package
          xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
    artifacts:
      - build/macos/**/*.pkg
    publishing:
      email:
        recipients:
          - ranierjardim@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false