name: ci_cd_utils_server
description: An empty application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  alfred: ^1.1.0+1
  args: ^2.4.0
  eosdart_ecc: ^0.4.4
  mongo_dart: ^0.9.1
  dio: ^5.0.3
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.21.6
